### ISSUE TITLE
memory

### ISSUE THREAD

**Issue by apt425410** [blacksourcez/MemoryX#1]
มันไม่ส่งค่าอะครับ ลองทำตามตัวอย่างดูแล้ว

**Comment by ayuthmang** [comment]
มีตัวอย่างการใช้งานมั้ยครับ มั้ยครับ

**Comment by apt425410** [comment]
MemoryX.Memory myProc = new MemoryX.Memory();

            string procName = "Game";
            int  address = 0x2d66e44;
            myProc.WriteMemory(address, new byte[] { 0x01,0x01 });
//ทดสอบใน c# winform

**Comment by ayuthmang** [comment]
ลอง Run As Admin ยังครับ

**Comment by apt425410** [comment]
ลองละครับ

**Comment by apt425410** [comment]
คุยเฟซได้ไหมครับ ทีมวิวมาดูให้หน่อยครับ

**Comment by ayuthmang** [comment]
ติดต่อยังไงดีครับ 5555555555555555

**Comment by apt425410** [comment]
ไม่มีเฟซหรอครับ

**Comment by ayuthmang** [comment]
ติดต่อทางข้อความบอร์ด bbs.cracker.in.th แล้วครับ

**Comment by apt425410** [comment]
โอเคครับ

**Comment by ayuthmang** [comment]
ต้อง GetProcessHandle( processName) ก่อนใช้นะครับ + Run As Admin ด้วย
